version: '2'

services:
  api-boilerplate:
    build:
      context: .
    volumes:
      - .:/www
      - /www/node_modules
    ports: 
      - "3000:3000"
    env-file:
      - .env
    links:
      - mongo
  mongo:
    image: "mongo:3.4"
    ports: "27017:27017"